package com.example.youtubedownloader

import android.content.Context
import android.util.Log
import java.io.File

object CookieHelper {

    private const val TAG = "CookieHelper"
    private const val COOKIE_FILE_NAME = "youtube_cookies.txt"

    fun getCookieFile(context: Context): File =
        File(context.filesDir, COOKIE_FILE_NAME)

    fun hasCookies(context: Context): Boolean {
        val file = getCookieFile(context)
        return file.exists() && file.length() > 100
    }

    fun saveCookiesFromWebView(context: Context): Boolean {
        try {
            val cookieManager = android.webkit.CookieManager.getInstance()
            val domains = listOf(
                "https://www.youtube.com",
                "https://youtube.com",
                "https://accounts.google.com",
                "https://m.youtube.com",
                "https://music.youtube.com"
            )

            val sb = StringBuilder()
            sb.appendLine("# Netscape HTTP Cookie File")
            sb.appendLine("# Generated by YT Downloader")
            sb.appendLine()

            var cookieCount = 0

            for (domain in domains) {
                val cookieString = cookieManager.getCookie(domain) ?: continue
                val domainHost = domain.removePrefix("https://")

                cookieString.split(";").forEach { cookie ->
                    val trimmed = cookie.trim()
                    val eqIndex = trimmed.indexOf('=')
                    if (eqIndex > 0) {
                        val name = trimmed.substring(0, eqIndex).trim()
                        val value = trimmed.substring(eqIndex + 1).trim()
                        sb.appendLine(
                            ".$domainHost\tTRUE\t/\tTRUE\t${
                                (System.currentTimeMillis() / 1000) + 31536000
                            }\t$name\t$value"
                        )
                        cookieCount++
                    }
                }
            }

            if (cookieCount == 0) return false

            getCookieFile(context).writeText(sb.toString())
            Log.d(TAG, "Saved $cookieCount cookies")
            return true
        } catch (e: Exception) {
            Log.e(TAG, "Failed to save cookies", e)
            return false
        }
    }

    fun clearCookies(context: Context) {
        try {
            getCookieFile(context).let { if (it.exists()) it.delete() }
            android.webkit.CookieManager.getInstance().removeAllCookies(null)
            android.webkit.CookieManager.getInstance().flush()
        } catch (_: Exception) {}
    }
}